export const keywordMap: Record<string, string[]> = {
  filter: ['fader', 'funnel', 'slider', 'tune', 'adjust', 'control', 'setting', 'sort'],
  settings: ['gear', 'cog', 'wrench', 'tool', 'config', 'preference', 'option', 'setting', 'control'],
  search: ['magnif', 'find', 'look', 'scan', 'zoom', 'glass', 'visual'],
  home: ['house', 'building', 'apartment', 'residence', 'cottage'],
  user: ['person', 'profile', 'account', 'avatar', 'human', 'man', 'woman', 'contact', 'team', 'group'],
  mail: ['envelope', 'email', 'message', 'letter', 'inbox', 'send', 'receive'],
  email: ['envelope', 'mail', 'message', 'letter', 'inbox'],
  calendar: ['date', 'schedule', 'event', 'day', 'month', 'time', 'appointment'],
  heart: ['like', 'love', 'favorite', 'bookmark', 'star'],
  favorite: ['star', 'heart', 'like', 'bookmark'],
  download: ['arrow', 'save', 'export', 'down', 'load'],
  upload: ['arrow', 'import', 'cloud', 'up', 'load'],
  trash: ['delete', 'remove', 'garbage', 'waste'],
  delete: ['trash', 'remove', 'garbage'],
  clear: ['delete', 'remove', 'garbage'],
  edit: ['pencil', 'write', 'modify', 'pen', 'compose'],
  write: ['pencil', 'edit', 'pen', 'compose', 'quill'],
  folder: ['directory', 'file', 'document', 'archive'],
  file: ['document', 'folder', 'page', 'paper'],
  image: ['photo', 'picture', 'media', 'camera', 'gallery'],
  photo: ['image', 'picture', 'camera', 'media'],
  video: ['movie', 'film', 'media', 'play', 'camera', 'youtube'],
  music: ['audio', 'sound', 'note', 'speaker', 'song', 'spotify'],
  audio: ['music', 'sound', 'speaker', 'volume', 'podcast'],
  lock: ['secure', 'password', 'key', 'private', 'safe'],
  unlock: ['open', 'key'],
  secure: ['lock', 'shield', 'safe', 'protection', 'security'],
  check: ['tick', 'done', 'complete', 'success', 'correct', 'mark', 'verify'],
  success: ['check', 'tick', 'done', 'complete'],
  close: ['x', 'exit', 'cancel', 'dismiss', 'remove'],
  exit: ['close', 'x', 'logout', 'leave', 'door'],
  add: ['plus', 'new', 'create', 'insert', 'team'],
  plus: ['add', 'new', 'create'],
  remove: ['minus', 'delete', 'subtract'],
  minus: ['remove', 'subtract'],
  arrow: ['chevron', 'caret', 'angle', 'direction', 'pointer', 'move'],
  menu: ['hamburger', 'nav', 'list', 'bars', 'line'],
  hamburger: ['menu', 'bars', 'list'],
  notification: ['bell', 'alert', 'ring', 'alarm'],
  bell: ['notification', 'alarm', 'alert'],
  warning: ['alert', 'caution', 'attention', 'danger', 'error', 'triangle'],
  error: ['warning', 'alert', 'x', 'danger'],
  info: ['information', 'help', 'question', 'about', 'circle'],
  help: ['question', 'info', 'support'],
  chart: ['graph', 'analytics', 'statistics', 'data', 'bar', 'line', 'pie', 'column', 'scatter'],
  graph: ['chart', 'analytics', 'data', 'statistics'],
  dollar: ['money', 'currency', 'cash', 'price', 'payment', 'coin'],
  money: ['dollar', 'cash', 'currency', 'coin', 'payment', 'exchange', 'wallet'],
  shopping: ['cart', 'bag', 'store', 'buy', 'basket', 'product'],
  cart: ['shopping', 'basket', 'bag', 'buy'],
  phone: ['call', 'mobile', 'device', 'telephone', 'smartphone'],
  call: ['phone', 'telephone', 'incoming', 'outgoing', 'missed', 'internal'],
  wifi: ['network', 'signal', 'connection', 'internet', 'wireless'],
  network: ['wifi', 'connection', 'internet', 'web'],
  battery: ['power', 'charge', 'energy'],
  power: ['battery', 'charge', 'energy', 'bolt', 'socket', 'plug'],
  clock: ['time', 'watch', 'alarm', 'timer', 'hour'],
  time: ['clock', 'watch', 'hour', 'half', 'quarter'],
  location: ['pin', 'map', 'marker', 'gps', 'place', 'navigate', 'offline'],
  map: ['location', 'navigate', 'direction', 'place', 'compass'],
  pin: ['location', 'marker', 'map', 'tack'],
  share: ['export'],
  send: ['share', 'forward', 'mail', 'arrow'],
  cloud: ['sync', 'backup', 'storage', 'upload', 'saving', 'weather'],
  sync: ['refresh', 'reload', 'update', 'cloud', 'rotate'],
  refresh: ['reload', 'sync', 'update', 'rotate'],
  copy: ['duplicate', 'clone'],
  paste: ['clipboard'],
  cut: ['scissors', 'trim'],
  print: ['printer'],
  save: ['disk', 'floppy', 'download'],
  undo: ['back', 'reverse', 'rotate'],
  redo: ['forward', 'repeat', 'rotate'],
  bold: ['text', 'format', 'strong'],
  italic: ['text', 'format', 'slant'],
  underline: ['text', 'format'],
  link: ['chain', 'url', 'hyperlink', 'connect'],
  unlink: ['chain', 'break'],
  expand: ['fullscreen', 'maximize', 'grow', 'arrow'],
  collapse: ['minimize', 'shrink', 'compress'],
  zoom: ['magnify', 'search', 'glass', 'circle'],
  play: ['video', 'audio', 'start', 'triangle'],
  pause: ['stop', 'wait', 'circle'],
  stop: ['pause', 'end', 'square', 'circle'],
  forward: ['next', 'skip', 'arrow'],
  backward: ['previous', 'back', 'arrow'],
  volume: ['sound', 'audio', 'speaker'],
  mute: ['silent', 'volume', 'quiet'],
  brightness: ['light', 'sun'],
  contrast: ['adjust'],
  sun: ['brightness', 'light', 'day', 'weather'],
  moon: ['night', 'dark', 'weather', 'cloud'],
  star: ['favorite', 'rating', 'bookmark'],
  weather: ['sun', 'moon', 'cloud', 'rain', 'snow', 'wind'],
  rain: ['weather', 'water', 'cloud', 'drop'],
  snow: ['weather', 'cold', 'winter'],
  wind: ['weather', 'air', 'power'],
  temperature: ['thermometer', 'hot', 'cold'],
  fire: ['flame', 'hot', 'burn'],
  water: ['drop', 'liquid', 'rain'],
  tree: ['nature', 'plant', 'forest'],
  leaf: ['nature', 'plant', 'green'],
  flower: ['nature', 'plant', 'blossom'],
  gift: ['present', 'box', 'package'],
  box: ['package', 'container', 'archive'],
  flag: ['banner', 'mark'],
  tag: ['label', 'bookmark', 'price'],
  label: ['tag', 'badge'],
  bookmark: ['favorite', 'save', 'mark'],
  book: ['read', 'library', 'page'],
  read: ['book', 'text', 'view'],
  graduation: ['education', 'school', 'cap', 'student'],
  school: ['education', 'learn', 'book', 'student'],
  science: ['lab', 'flask', 'experiment'],
  medical: ['health', 'hospital', 'medicine', 'doctor', 'ambulance'],
  health: ['medical', 'heart', 'fitness'],
  fitness: ['health', 'sport', 'exercise'],
  sport: ['game', 'ball', 'fitness', 'tennis', 'golf'],
  game: ['play', 'controller', 'sport'],
  trophy: ['award', 'win', 'prize'],
  award: ['trophy', 'medal', 'prize'],
  target: ['aim', 'goal', 'bullseye'],
  rocket: ['launch', 'space', 'speed'],
  airplane: ['flight', 'travel', 'plane', 'takeoff', 'landing'],
  car: ['vehicle', 'auto', 'drive', 'signal'],
  train: ['rail', 'metro', 'subway'],
  bus: ['vehicle', 'transport'],
  bicycle: ['bike', 'cycle'],
  walk: ['pedestrian', 'foot'],
  compass: ['direction', 'navigate', 'orientation'],
  globe: ['world', 'earth', 'planet', 'international'],
  translate: ['language', 'global'],
  mic: ['microphone', 'record', 'audio'],
  microphone: ['mic', 'record', 'audio'],
  camera: ['photo', 'picture', 'video'],
  code: ['programming', 'developer', 'brackets', 'typescript', 'javascript'],
  programming: ['code', 'developer', 'algorithm'],
  developer: ['code', 'programming'],
  terminal: ['console', 'command', 'cli'],
  console: ['terminal', 'debug'],
  bug: ['error', 'debug', 'issue'],
  debug: ['bug', 'console', 'error'],
  database: ['data', 'storage', 'server'],
  server: ['database', 'cloud', 'network'],
  monitor: ['screen', 'display', 'computer'],
  desktop: ['computer', 'pc', 'monitor'],
  laptop: ['computer', 'notebook', 'remove'],
  mobile: ['phone', 'smartphone', 'device', 'navigator'],
  tablet: ['ipad', 'device'],
  keyboard: ['type', 'input'],
  mouse: ['cursor', 'pointer', 'click', 'left', 'right'],
  usb: ['drive', 'storage', 'cable'],
  bluetooth: ['wireless', 'connection'],
  connection: ['link', 'network', 'chain'],
  text: ['font', 'type', 'align', 'format', 'firstline'],
  align: ['left', 'right', 'center', 'justify', 'top', 'bottom'],
  loading: ['spinner', 'progress', 'wait', 'reload'],
  spinner: ['loading', 'progress'],
  progress: ['loading', 'bar'],
  circle: ['round', 'dot', 'ring'],
  square: ['box', 'rectangle'],
  rectangle: ['square', 'box'],
  triangle: ['shape', 'arrow'],
  rotate: ['turn', 'spin', 'angle', 'refresh'],
  flip: ['mirror', 'reverse'],
  sort: ['filter', 'order', 'arrange'],
  grid: ['layout', 'view', 'table'],
  list: ['menu', 'view'],
  table: ['grid', 'data', 'column', 'row'],
  row: ['table', 'line'],
  column: ['table', 'vertical'],
  layer: ['stack', 'mask'],
  mask: ['layer', 'hide'],
  eye: ['view', 'show', 'visible'],
  hide: ['invisible', 'mask'],
  visible: ['eye', 'show'],
  invisible: ['hide', 'eye'],
  toggle: ['switch', 'button'],
  switch: ['toggle', 'button'],
  button: ['click', 'press'],
  radio: ['select', 'choice'],
  checkbox: ['check', 'select'],
  input: ['field', 'form', 'text'],
  form: ['input', 'field'],
  select: ['dropdown', 'choose'],
  dropdown: ['select', 'menu'],
  slider: ['range', 'fader', 'control'],
  range: ['slider', 'fader'],
  color: ['palette', 'paint'],
  palette: ['color', 'paint'],
  paint: ['brush', 'color'],
  brush: ['paint', 'draw'],
  draw: ['pencil', 'pen', 'sketch'],
  sketch: ['draw', 'pencil'],
  crop: ['cut', 'trim', 'image'],
  resize: ['scale', 'transform'],
  transform: ['resize', 'rotate', 'scale'],
  scale: ['resize', 'zoom'],
  gradient: ['color', 'blend'],
  blend: ['mix', 'gradient'],
  opacity: ['transparency', 'alpha'],
  shadow: ['drop', 'effect'],
  blur: ['effect', 'focus'],
  focus: ['blur', 'sharp'],
  sharp: ['focus', 'clear'],
  archive: ['box', 'storage', 'folder'],
  compress: ['zip', 'archive'],
  extract: ['unzip', 'decompress'],
  widget: ['component', 'module'],
  component: ['module', 'widget'],
  module: ['component', 'package'],
  package: ['box', 'bundle', 'module'],
  bundle: ['package', 'group'],
  group: ['team', 'collection', 'bundle'],
  collection: ['group', 'set'],
  set: ['collection', 'group'],
  layout: ['grid', 'arrange'],
  arrange: ['sort', 'order', 'layout'],
  order: ['sort', 'arrange'],
  hierarchy: ['tree', 'structure'],
  structure: ['hierarchy', 'tree'],
  organization: ['hierarchy', 'structure'],
  path: ['route', 'way', 'road'],
  route: ['path', 'way'],
  road: ['path', 'route', 'street'],
  navigate: ['map', 'direction', 'compass'],
  direction: ['arrow', 'navigate', 'compass'],
  distance: ['measure', 'ruler'],
  measure: ['ruler', 'distance'],
  ruler: ['measure', 'distance'],
  angle: ['rotate', 'degree'],
  degree: ['angle', 'temperature'],
  percent: ['percentage', 'ratio'],
  percentage: ['percent', 'ratio'],
  ratio: ['percent', 'proportion'],
  calculator: ['math', 'compute'],
  math: ['calculator', 'compute', 'formula'],
  compute: ['calculator', 'math'],
  formula: ['math', 'equation'],
  equation: ['formula', 'math'],
  function: ['formula', 'code'],
  variable: ['code', 'math'],
  equal: ['sign', 'math'],
  not: ['negation', 'false'],
  and: ['logic', 'operator'],
  or: ['logic', 'operator'],
  if: ['conditional', 'logic'],
  else: ['conditional', 'logic'],
  loop: ['repeat', 'cycle'],
  repeat: ['loop', 'cycle'],
  cycle: ['loop', 'repeat'],
  break: ['stop', 'end'],
  continue: ['next', 'skip'],
  return: ['back', 'result'],
  result: ['output', 'answer'],
  output: ['result', 'export'],
  enter: ['input', 'import'],
  imports: ['load', 'enter'],
  exports: ['save', 'output'],
  load: ['import', 'open'],
  open: ['unlock', 'file'],
  new: ['add', 'create', 'plus'],
  create: ['new', 'add', 'make'],
  make: ['create', 'build'],
  build: ['make', 'construct'],
  construct: ['build', 'create']
};
